//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the ApplicationData datasource.
    /// </summary>
    public sealed partial class ApplicationDataService
        : global::LightSwitchApplication.ApplicationData
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ApplicationDataService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_Inserting(global::LightSwitchApplication.Menu entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_Inserted(global::LightSwitchApplication.Menu entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_Updating(global::LightSwitchApplication.Menu entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_Updated(global::LightSwitchApplication.Menu entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_Deleting(global::LightSwitchApplication.Menu entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_Deleted(global::LightSwitchApplication.Menu entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_Validate(global::LightSwitchApplication.Menu entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Menu, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_Inserting(global::LightSwitchApplication.MenuTile entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_Inserted(global::LightSwitchApplication.MenuTile entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_Updating(global::LightSwitchApplication.MenuTile entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_Updated(global::LightSwitchApplication.MenuTile entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_Deleting(global::LightSwitchApplication.MenuTile entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_Deleted(global::LightSwitchApplication.MenuTile entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_Validate(global::LightSwitchApplication.MenuTile entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.MenuTile, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TilesForMenu_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void TilesForMenu_Executing(string MenuName);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TilesForMenu_PreprocessQuery(string MenuName, ref global::System.Linq.IQueryable<global::LightSwitchApplication.MenuTile> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void TilesForMenu_Executed(string MenuName, global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.MenuTile> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void TilesForMenu_ExecuteFailed(string MenuName, global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executing(global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executed(global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_ExecuteFailed(global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Menu>
                __MenusEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Menu>(
                    "Menus",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_Filter);
            private static bool __Menus_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Menus_CanInsert(ref result);
                return result;
            }
            private static bool __Menus_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Menus_CanUpdate(ref result);
                return result;
            }
            private static bool __Menus_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Menus_CanDelete(ref result);
                return result;
            }
            private static bool __Menus_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Menus_CanRead(ref result);
                return result;
            }
            private static void __Menus_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Menu e)
            {
                d.Menus_Inserting(e);
            }
            private static void __Menus_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Menu e)
            {
                d.Menus_Inserted(e);
            }
            private static void __Menus_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Menu e)
            {
                d.Menus_Updating(e);
            }
            private static void __Menus_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Menu e)
            {
                d.Menus_Updated(e);
            }
            private static void __Menus_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Menu e)
            {
                d.Menus_Deleting(e);
            }
            private static void __Menus_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Menu e)
            {
                d.Menus_Deleted(e);
            }
            private static void __Menus_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Menu e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Menus_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Menu, bool>> __Menus_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Menu, bool>> filter = null;
                d.Menus_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.MenuTile>
                __MenuTilesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.MenuTile>(
                    "MenuTiles",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_Filter);
            private static bool __MenuTiles_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.MenuTiles_CanInsert(ref result);
                return result;
            }
            private static bool __MenuTiles_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.MenuTiles_CanUpdate(ref result);
                return result;
            }
            private static bool __MenuTiles_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.MenuTiles_CanDelete(ref result);
                return result;
            }
            private static bool __MenuTiles_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.MenuTiles_CanRead(ref result);
                return result;
            }
            private static void __MenuTiles_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MenuTile e)
            {
                d.MenuTiles_Inserting(e);
            }
            private static void __MenuTiles_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MenuTile e)
            {
                d.MenuTiles_Inserted(e);
            }
            private static void __MenuTiles_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MenuTile e)
            {
                d.MenuTiles_Updating(e);
            }
            private static void __MenuTiles_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MenuTile e)
            {
                d.MenuTiles_Updated(e);
            }
            private static void __MenuTiles_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MenuTile e)
            {
                d.MenuTiles_Deleting(e);
            }
            private static void __MenuTiles_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MenuTile e)
            {
                d.MenuTiles_Deleted(e);
            }
            private static void __MenuTiles_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MenuTile e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.MenuTiles_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.MenuTile, bool>> __MenuTiles_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.MenuTile, bool>> filter = null;
                d.MenuTiles_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>(
                    "SaveChanges",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.MenuTile>
                __TilesForMenuEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.MenuTile>(
                    "TilesForMenu",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TilesForMenu_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TilesForMenu_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TilesForMenu_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TilesForMenu_Failed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TilesForMenu_PreprocessQuery);
            private static bool __TilesForMenu_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.TilesForMenu_CanExecute(ref r);
                return r;
            }
            private static void __TilesForMenu_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.TilesForMenu_Executing((string)args[0]);
            }
            private static void __TilesForMenu_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.TilesForMenu_Executed((string)args[0], (global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.MenuTile>)args[1]);
            }
            private static void __TilesForMenu_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.TilesForMenu_ExecuteFailed((string)args[0], ex);
            }
            private static global::System.Linq.IQueryable __TilesForMenu_PreprocessQuery(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.MenuTile> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.MenuTile>)args[1];
                d.TilesForMenu_PreprocessQuery((string)args[0], ref query);
                return query;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>
                ___QueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>(
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Failed);
            private static void __Query_Executing(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor)
            {
                d.Query_Executing(queryDescriptor);
            }
            private static void __Query_Executed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor)
            {
                d.Query_Executed(queryDescriptor);
            }
            private static void __Query_Failed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor)
            {
                d.Query_ExecuteFailed(queryDescriptor);
            }
        }
    
        #endregion
    }
    
    #endregion
}
