// Warning: AutoGenerated file, Don't edit.
document.writeln("<script type=\"text/javascript\" src=\"Screens/AdminMenu.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/MenuView.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/Start.lsml.js\"></script>");
